Add check ensuring the right number of opcodes
Fantom-foundation/Tosca pull request #458
Opened 2024-05-08 09:17 UTC by simonlechner

Due to the huge state space finding missing opcodes requires the evaluation of millions of states. A simple check is introduced which ensures that the number of implemented opcodes is consistent with evm codes website.
Has to be merged after the implementation of BLOCKHASH.

2024-05-09 08:07 UTC, HerbertJordan approved these changes

2024-05-09 08:07 UTC, HerbertJordan commented on go/ct/common/opcodes_test.go
The PR description states that this change is checking the number of *implemented* OpCodes. However, the test only covers the number (actually the set) of defined OpCodes.

Should we add a test in the specification package that checks that all valid OpCodes have some rules?

2024-05-13 06:49 UTC, simonlechner commented on go/ct/common/opcodes_test.go
I changed the PR description to "the number of defined opcodes". 

Yes, such a test could be a nice addition.

2024-06-10 09:41 UTC, facuMH commented
`BLOCKHASH` has already been merged. And now there is support for Paris and Shanghai revisions. Maybe we can rebase this PR.

2024-06-10 11:05 UTC, HerbertJordan requested changes

2024-06-10 11:05 UTC, HerbertJordan commented on go/ct/common/opcodes_test.go
> +		0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0A, 0x0B,
It would be great to have the actual OpCode constants here, instead of their values.

So, for instance `[]OpCode{STOP, ADD, MUL}`.

2024-06-10 12:59 UTC, HerbertJordan approved these changes
Thanks!

2024-06-10 13:41 UTC, facuMH approved these changes

2024-06-11 09:09 UTC, merged