evmzero:  Add check for range in blockHash op
Fantom-foundation/Tosca pull request #461
Opened 2024-05-14 10:26 UTC by facuMH

This PR fixes the BLOCKHASH operation by adding a check that the number of the block to be hashed is within 256 of the current block.
It also adds a test for the case when the block to be hashed is outside of this range, in this case the returned hash is 0.

2024-05-14 13:28 UTC, HerbertJordan requested changes

2024-05-14 13:28 UTC, HerbertJordan commented on cpp/vm/evmzero/interpreter.cc
>      int64_t number = static_cast<int64_t>(top[0]);
This function does not check for overflows, but I guess it should.

2024-05-14 13:28 UTC, HerbertJordan commented on cpp/vm/evmzero/interpreter_test.cc
> +
Please also add test cases for edge cases where the provided number is
- equal to the current block - {0, 1, 255, 256, 257}
- an overflow that would result in a valid value if truncated

2024-05-21 09:46 UTC, HerbertJordan approved these changes
Thanks for fixing this.

2024-05-21 09:48 UTC, simonlechner commented on cpp/vm/evmzero/interpreter.cc
> +    }
I think the reason why these checks are necessary deserves a comment.

2024-05-21 09:48 UTC, simonlechner commented on cpp/vm/evmzero/interpreter_test.cc
> +  //     .WillOnce(Return(evmc_tx_context{.block_number = block_number}));
Should this commented code be removed?

2024-05-21 13:02 UTC, LuisPH3 approved these changes

2024-05-27 11:58 UTC, HerbertJordan approved these changes
Looks good, thanks.

2024-05-27 12:01 UTC, merged