CT: fix in TestCt_ExplicitCases
Fantom-foundation/Tosca pull request #483
Opened 2024-05-29 09:44 UTC by facuMH

This test was relying on the random number generator using always the same seed and being used the same number of times. As elements were added to the state generator, this test stopped working. With this fix we can always ensure that the test runs with states generated with supported revision by the CT and the implementations.

2024-05-29 09:49 UTC, HerbertJordan requested changes

2024-05-29 09:49 UTC, HerbertJordan commented on go/ct/evm_test.go
> +			RevisionBounds(R07_Istanbul, R10_London), // TODO: update to newer revisions as suppor is added
Please use the [NewestSupportedRevision](https://github.com/Fantom-foundation/Tosca/blob/bc85fbcf8f913ead471a408e81f38295f5986ac3/go/ct/common/revisions.go#L34) constant here and below.

2024-05-29 10:52 UTC, HerbertJordan approved these changes

2024-05-29 13:05 UTC, LuisPH3 approved these changes
What are explicit cases?

2024-05-31 07:13 UTC, simonlechner approved these changes

2024-05-31 09:12 UTC, merged