CT: update specification
Fantom-foundation/Tosca pull request #518
Opened 2024-06-10 09:40 UTC by facuMH

This PR updates a few specification rules so that they can also accept states with Paris and Shanghai revisions.

2024-06-10 10:07 UTC, simonlechner commented on go/ct/spc/specification.go
> +				// Lt(StackSize(), st.MaxStackSize),
Please remove commented out code.

2024-06-10 10:09 UTC, LuisPH3 requested changes
Just some small details

2024-06-10 10:09 UTC, LuisPH3 commented on go/ct/spc/specification.go
> +	selfDestructRevisions := []Revision{R07_Istanbul, R09_Berlin, R10_London, R11_Paris, R12_Shanghai}
newest supported?

2024-06-10 10:09 UTC, LuisPH3 commented on go/ct/spc/specification.go
> +		for _, rev := range []Revision{R07_Istanbul, R09_Berlin, R10_London, R11_Paris, R12_Shanghai} {
```suggestion
		for i := R07_Istanbul; i <= NewestSupportedRevision; i++  {
```

2024-06-10 10:09 UTC, LuisPH3 commented on go/ct/spc/specification.go
> +				// Lt(StackSize(), st.MaxStackSize),
dead code

2024-06-10 13:18 UTC, LuisPH3 submitted a review, later dismissed

2024-06-11 07:16 UTC, simonlechner submitted a review, later dismissed

2024-06-11 09:49 UTC, HerbertJordan approved these changes

2024-06-11 09:49 UTC, HerbertJordan commented on go/ct/spc/specification.go
> +	for rev := R10_London; rev <= R12_Shanghai; rev++ {
Would it be wrong to include `Cancun` already? Maybe even even using `NewestSupportedRevision` as the upper end?

2024-06-11 12:11 UTC, LuisPH3 approved these changes

2024-06-11 12:44 UTC, merged