CT: reusable sample slices
Fantom-foundation/Tosca pull request #559
Opened 2024-06-26 12:27 UTC by facuMH

This PR is a response to the test `TestSpecification_EachRuleProducesAMatchingTestCase` taking too long for the development cycle compared to other tests.
Running the commands
```
go test ./go/ct/spc -run ^TestSpecification_EachRuleProducesAMatchingTestCase$ -cpuprofile cpu.log
go tool pprof -http "localhost:8000" ./cpu.log
````
and a followed analysis showed that `MemorySizeParameter.Samples()`  took about 30% of the whole run.
Making the slice a global variable to prevent multiple allocations reduced the runtime of the whole test in ~45%
Making the slice for `MemoryOffsetParameter.Samples()` reusable as well reduced another ~5%. 
The rest of the parameters are made reusable as well for consistency. 

This change is "safe" only because the `.Samples` methods are only called in a `for _, value := range param.Samples()` so the slices can not be modified. A comment is added to reflect this warning.

2024-06-26 13:51 UTC, HerbertJordan requested changes

2024-06-26 13:51 UTC, HerbertJordan commented on go/ct/rlz/parameters.go
> +	// this has to be insured by the users of this interface.
```suggestion
	// Samples returns a list of test values for an operation parameter.
	// For efficiency reasons, the resulting slice may be shared among
	// multiple calls. Thus, neither the slice itself nor its elements must
	// be modified by users of this function.
```

2024-06-26 13:51 UTC, HerbertJordan commented on go/ct/rlz/parameters.go
> +var NumericParameterSamples = []U256{
This and all other lists should be private.

2024-06-27 07:21 UTC, simonlechner approved these changes
Nice change with surprisingly big impact on the runtime.

2024-06-27 08:44 UTC, HerbertJordan approved these changes

2024-06-27 12:12 UTC, merged