CT: extcodehash pre berlin
Fantom-foundation/Tosca pull request #591
Opened 2024-07-04 14:07 UTC by facuMH

This PR improves the coverage of `EXTCODEHASH` rule by dividing the `preBerlin` rule into `warm` and `cold` cases, ensuring all branches are covered.

2024-07-05 06:54 UTC, HerbertJordan requested changes

2024-07-05 06:54 UTC, HerbertJordan commented on go/ct/spc/specification.go
> +			s.Stack.Push(NewU256FromBytes(hash[:]...))
I am not sure which branch coverage is increased by this change. Can you add a before / after to the description of the PR?

If the branch that was not covered was the first branch in
```
if !s.Accounts.Exist(address) {
  s.Stack.Push(NewU256(0))
} else {
  hash := s.Accounts.GetCodeHash(address)
  s.Stack.Push(NewU256FromBytes(hash[:]...))
}
```
wouldn't it be easiest to just replace the effect with
```
address := NewAddress(s.Stack.Pop())
hash := s.Accounts.GetCodeHash(address)
s.Stack.Push(NewU256FromBytes(hash[:]...))
```
and eliminate the branch that was not covered?

It seems odd to add a condition on whether an address is warm or cold to the rule if in the effect this property is not used. This kinda indicates that a `IsAddressWarm` condition has a side effect that is exploited here -- namely that any any warm account exists. This would be a bug in the constraint solver handling warm addresses. There may be warm addresses that not point to existing accounts.

2024-07-05 07:53 UTC, facuMH commented on go/ct/spc/specification.go
> +			s.Stack.Push(NewU256FromBytes(hash[:]...))
after a brief conversation online, we agreed that the interpreter should not check whether the account exists or not, and simply get the code hash from the stateDB, and the latter should return 0 when needed.

2024-07-05 08:28 UTC, HerbertJordan submitted a review, later dismissed

2024-07-05 08:28 UTC, HerbertJordan commented on go/ct/spc/specification.go
> +	extCodeHashEffect := func(s *st.State, address tosca.Address) {
nit: popping the address from the stack in the state could be also moved into this function.

2024-07-05 15:56 UTC, HerbertJordan approved these changes

2024-07-08 06:31 UTC, simonlechner approved these changes

2024-07-08 08:23 UTC, merged