add evmrs and rust ci
Fantom-foundation/Tosca pull request #652
Opened 2024-08-19 12:40 UTC by LorenzSchueler

- add emvrs crate with a single unit test
- add ci (GH action) for Rust
- doc Rust build in BUILD.md

2024-08-19 12:49 UTC, LuisPH3 approved these changes

2024-08-19 12:49 UTC, LuisPH3 commented on .github/workflows/rust.yaml
> +    branches: [ main, evmrs ]
please only trigger CI if rust code is affected:
```
    paths:
      - '**.rs''
      - 'Cargo.*'
```

2024-08-19 12:59 UTC, HerbertJordan requested changes
Are the `Cargo.*` files on the root level required?

2024-08-19 13:04 UTC, LorenzSchueler commented on rust/Cargo.toml
> +edition = "2021"
2021 is the current Rust edition. The 2024 edition is expected to be released at the beginning of next year.

2024-08-19 13:24 UTC, LuisPH3 commented on Cargo.toml
Because of symmetry with C++, It would be nice to have them inside the rust directory. This can be done by changing directory during build, just like c++ does in the Makefile. 
- Downside is that we loose IDE integration features. This is the same problem with the c++ project.

2024-08-20 12:04 UTC, LorenzSchueler commented on Cargo.toml
I moved it into `/rust`

2024-08-20 14:19 UTC, closed without merging