LFVM: add hash cache tests
Fantom-foundation/Tosca pull request #664
Opened 2024-08-22 14:21 UTC by facuMH

This PR renames the `HashCache` type to `hashCache` to make it private, renames the static variable `hashCache` to `hashVault`, adds tests for the hash cache and removes `hash_cache.go` from the override list.

2024-08-22 14:44 UTC, LuisPH3 commented
> This PR renames the `HashCache` type to `hashCache` to make it private, renames the static variable `hashCache` to `hashVault`, adds tests for the hash cache and removes `hash_cache.go` from the override list.
> 
> it also removes an `else` case from `getHashXX`. This `else` can never happen since the first time an element is added it would create a `head` and this is always updated, but never set to nil. The only case where this "could" happen is if calling `hashCache{}` instead of calling `newHashCache` function, and even then the program would crash when trying to add the first element, not even reaching the point of getting the hash for an existing entry whose `succ` is nil.

Note, this description is fine, but first you could say what was the problem (someone calls wrong constructor), and afterwards the action taken (make type private).

2024-08-22 14:46 UTC, LuisPH3 submitted a review, later dismissed

2024-08-22 14:46 UTC, LuisPH3 commented on go/interpreter/lfvm/instructions.go
> +var hashVault = newHashCache(1<<16, 1<<18)
:thinking: just `cache`?  `sha3Cache`?

2024-08-22 15:23 UTC, HerbertJordan requested changes
> it also removes an else case from getHashXX. This else can never happen since the first time an element is added it would create a head and this is always updated, but never set to nil. The only case where this "could" happen is if calling hashCache{} instead of calling newHashCache function, and even then the program would crash when trying to add the first element, not even reaching the point of getting the hash for an existing entry whose succ is nil.

This argument is wrong (see comment) and I think removing those `else` branches breaks the cache.

2024-08-22 15:23 UTC, HerbertJordan commented on go/interpreter/lfvm/hash_cache.go
> -				h.tail32 = entry.pred
This line of code is triggered if the very last element in the cache is touched and moved to the front. An example test provoking it is this:
```
func TestHashCache_TouchLastElement(t *testing.T) {
	ctxt := &context{}
	cache := newHashCache(3, 3)
	cache.getHash32(ctxt, []byte{byte(1)})
	cache.getHash32(ctxt, []byte{byte(2)})
	cache.getHash32(ctxt, []byte{byte(3)})
	cache.getHash32(ctxt, []byte{byte(1)})
}
```
Without this line the tail would end up pointing to the head when touching the last element in the LRU list and the LRU order is destroyed.

2024-08-22 15:23 UTC, HerbertJordan commented on go/interpreter/lfvm/instructions.go
> +var hashVault = newHashCache(1<<16, 1<<18)
I like `sha3Cache` ...

2024-08-23 09:27 UTC, LuisPH3 approved these changes

2024-08-26 07:53 UTC, simonlechner approved these changes

2024-08-26 08:21 UTC, HerbertJordan requested changes
I think the way the hash cache is tested needs to be rethought. Substantial properties are not tested, including its thread safety and the node replacement policy. See, for example, these [tests](https://github.com/Fantom-foundation/Carmen/blob/main/go/database/mpt/node_cache_test.go) for the node cache in Carmen for reference.

We should discuss the general testing approach before moving forward.

2024-08-26 08:21 UTC, HerbertJordan commented on go/interpreter/lfvm/hash_cache_test.go
> +func TestHashCache_useCacheTail32(t *testing.T) {
I think those tests are unnecessarily convoluted and seem to be mainly focused on pushing coverage up. These tests are not sufficient to test the actual requirements on the hash cache.

2024-08-27 09:20 UTC, facuMH commented
the hash cache will undergo some refactoring, and the testing will get a new approach, hence I'm closing this PR

2024-08-27 09:20 UTC, closed without merging