Floria: Add access list
Fantom-foundation/Tosca pull request #731
Opened 2024-09-05 07:48 UTC by simonlechner

This PR adds the access list introduced in the Berlin revision to Floria.
The integration test scenario had to been changed to also deal with keys. The current implementation requires an iteration through all (worst case) entries which is not performant but should not be a problem for the scenario, which is only used in tests.  
Contributes to #714.

2024-09-05 08:07 UTC, facuMH approved these changes
looks good. I got a little intrigued about the difference in performance between `map` search and `slice` search (iteration). if you could provide a little info on this, that would be great.

2024-09-05 09:59 UTC, simonlechner commented on go/integration_test/processor/scenario.go
> +	for _, tuple := range c.accessList {
I don't think a benchmark will be necessary. Here is a quick reminder on search complexities of maps and slices: https://stackoverflow.com/a/18863041

2024-09-05 14:30 UTC, LuisPH3 approved these changes

2024-09-06 07:10 UTC, facuMH submitted a review, later dismissed

2024-09-06 08:45 UTC, HerbertJordan requested changes
Looks good, some minor requests for changes.

2024-09-06 08:45 UTC, HerbertJordan commented on go/processor/floria/precompiled.go
> +func getPrecompiledContracts(address tosca.Address, revision tosca.Revision) map[common.Address]geth.PrecompiledContract {
This function does not need the `address` parameter.

2024-09-06 08:45 UTC, HerbertJordan commented on go/processor/floria/processor.go
> +		context.AccessStorage(*transaction.Recipient, tosca.Key{})
Should this use [`AccessAccount`](https://github.com/Fantom-foundation/Tosca/blob/cd54781393a81426f6174a67d8a6b08b95677a9d/go/tosca/interpreter.go#L95) instead?

2024-09-06 08:45 UTC, HerbertJordan commented on go/processor/floria/processor.go
> +		context.AccessStorage(address, tosca.Key{})
Also here, use `AccessAccount`?

2024-09-06 08:45 UTC, HerbertJordan commented on go/processor/floria/processor_test.go
> +	ctrl.Finish()
This should not be needed. If you initialize the controller with `t` it will add automatically an end-of-test callback to finalize the controller.

2024-09-06 11:10 UTC, HerbertJordan approved these changes

2024-09-06 11:42 UTC, LuisPH3 approved these changes

2024-09-06 11:59 UTC, facuMH approved these changes

2024-09-06 12:00 UTC, merged