Evmrs go integration
Fantom-foundation/Tosca pull request #778
Opened 2024-09-17 12:19 UTC by LorenzSchueler

- build evmrs using make by invoking `cargo`
- integrate emvrs into Tosca

2024-09-18 13:03 UTC, simonlechner requested changes
Looks good.
Please update requirements and build instructions since you are changing the Makefile.

2024-09-18 13:14 UTC, LorenzSchueler commented on go/interpreter/evmrs/ct_test.go
> +		byte(vm.ADD),
Sure. However, I just copied it from evmzero. Should I leave it as is for consistency or update both?

2024-09-18 13:15 UTC, LorenzSchueler commented on Makefile
> +tosca-go: tosca-cpp tosca-rust evmone
The instructions are already in `BUILD.md`, but they were outdated. Are updated now.

2024-09-18 13:16 UTC, LorenzSchueler commented on go/interpreter/evmrs/evmrs_test.go
They are just copied from `evmzero`.

2024-09-18 14:50 UTC, LuisPH3 commented on go/interpreter/evmrs/ct_test.go
> +		byte(vm.ADD),
Don't update evmzero, you can define your own tests in this namespace. Evmzero is pending a large refactor and testing effort, some day.

2024-09-18 15:01 UTC, LuisPH3 reviewed
I got cold feet with this, let me check first what are the implications. Since aida calls our makefile, it will require rust everywhere.

2024-09-19 07:14 UTC, HerbertJordan approved these changes
The Go integration code looks good to me. I also managed to build and run it on my local system. So from my side it is an approval.

However, please work with @LuisPH3 and @simonlechner on making sure build dependencies are covered on Jenkins.

2024-09-19 07:14 UTC, HerbertJordan commented on go/interpreter/evmrs/ct_test.go
> +	// Compile time check that ctAdapter implements the st.Evm interface.
```suggestion
	// Compile time check that ctAdapter implements the ct.Evm interface.
```

2024-09-19 07:14 UTC, HerbertJordan commented on go/interpreter/evmrs/evmrs_test.go
> +	t.Skip("evmrs does not implement the profiling configuration yet") // TODO
Right, if it is not supported yet, just drop the test.

If you want to make sure it is not supported, have a test like
```
        instance, err := tosca.NewInterpreter("evmrs")
	if err != nil {
		t.Fatalf("failed to load evmrs interpreter: %v", err)
	}
	_, ok := instance.(tosca.ProfilingInterpreter)
	if ok {
		t.Fatalf("evmrs should not support profiling")
	}
```

2024-09-20 10:59 UTC, simonlechner submitted a review, later dismissed
As soon as we know that this wont break anybodies build it good to merge from my side.

2024-09-26 12:50 UTC, LuisPH3 commented
I have been checking what can fail once this pr is merged,
Pipelines in https://github.com/Fantom-foundation/LaScala/tree/main/tosca will stop working because two reasons: 

- [ ] GCP image does not have rust:  both "quick" and "db-small-ssd" have rust installed 
- [ ] pipeline does not add rust to the jenkins user path.

2024-10-01 13:01 UTC, merged