evmrs: add feature "dump-cov" and bash script to collect CT coverage data
Fantom-foundation/Tosca pull request #832
Opened 2024-10-01 14:19 UTC by LorenzSchueler

2024-10-01 14:21 UTC, LorenzSchueler commented
I'll wait until #826 is merged because I want to include documentation in BUILD.md for this but maybe @LuisPH3 you can have a look at in in the meantime anyway.

2024-10-02 09:43 UTC, LuisPH3 requested changes
When we implemented the C++ coverage, we agreed on adding a test to verify that the infrastructure is working.
The reason is that these mechanisms are rather flimsy and could silently stop working, specially when not used for a while. 

Please take a look on go/lib/cpp/coverage_test.go, and the last stage on the jenkins file. And try to repeat this patern. 
- build again with coverage enabled.
- run the go-test that checks that coverage data has been generated.

2024-10-02 15:22 UTC, LorenzSchueler commented
The fix in the last commit is dirty but it was the only way I could find to get it to work.

2024-10-03 07:50 UTC, LuisPH3 approved these changes

2024-10-03 10:54 UTC, merged